# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5d92e005551897f513f2a175264e249e3f84d72b0ccc7e6baacc8c5002f035a2c9dda6bb63349d1b56744cc775f13088d0bff4ec6efe61782f1572e91c08a9a

test:
  secret_key_base: c3ec4a6b44637a8bff639e30895d6022f31d89560a64e3df317c38d1663d1a527376da908cf036cc2a5028f63774c89895652419543fdbf080333d61a36055cd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
